// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: ocis-eosprojects.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for EosProjects service

func NewEosProjectsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for EosProjects service

type EosProjectsService interface {
	GetProjects(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type eosProjectsService struct {
	c    client.Client
	name string
}

func NewEosProjectsService(name string, c client.Client) EosProjectsService {
	return &eosProjectsService{
		c:    c,
		name: name,
	}
}

func (c *eosProjectsService) GetProjects(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "EosProjects.GetProjects", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EosProjects service

type EosProjectsHandler interface {
	GetProjects(context.Context, *Request, *Response) error
}

func RegisterEosProjectsHandler(s server.Server, hdlr EosProjectsHandler, opts ...server.HandlerOption) error {
	type eosProjects interface {
		GetProjects(ctx context.Context, in *Request, out *Response) error
	}
	type EosProjects struct {
		eosProjects
	}
	h := &eosProjectsHandler{hdlr}
	return s.Handle(s.NewHandler(&EosProjects{h}, opts...))
}

type eosProjectsHandler struct {
	EosProjectsHandler
}

func (h *eosProjectsHandler) GetProjects(ctx context.Context, in *Request, out *Response) error {
	return h.EosProjectsHandler.GetProjects(ctx, in, out)
}
